name: Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
          always-auth: true
      - name: Configure npm auth
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
          npm --version
          npm whoami || true
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Publish
        id: publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          set -o pipefail
          npm publish --access public 2>&1 | tee publish.log
          echo "code=$?" >> "$GITHUB_OUTPUT"
      - name: Upload publish log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: publish-log
          path: publish.log
      - name: Fail if publish failed
        if: steps.publish.outputs.code != '0'
        run: |
          echo "Publish failed"
          exit 1
